# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKAMMR', '0003_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
