# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SKAMMR', '0006_postmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostModel',
        ),
    ]
